var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/cron/abandoned-cart/route.js")
R.c("server/chunks/[root-of-the-server]__1m7bwvz._.js")
R.c("server/chunks/node_modules_0ub6ovm._.js")
R.c("server/chunks/_1n7i2mp._.js")
R.c("server/chunks/_1ue59d7._.js")
R.c("server/chunks/[root-of-the-server]__0g0zd0c._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/_next-internal_server_app_api_cron_abandoned-cart_route_actions_1qzk_w3.js")
R.m(853727)
module.exports=R.m(853727).exports
