var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/cart/recover/route.js")
R.c("server/chunks/[root-of-the-server]__1rqvgb8._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/_1n7i2mp._.js")
R.c("server/chunks/[root-of-the-server]__0g0zd0c._.js")
R.c("server/chunks/_0o550kv._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/_next-internal_server_app_api_cart_recover_route_actions_0h7o55t.js")
R.m(69079)
module.exports=R.m(69079).exports
