var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/orders/[id]/approve-binance/route.js")
R.c("server/chunks/[root-of-the-server]__16uzxjs._.js")
R.c("server/chunks/_1n7i2mp._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/_0o550kv._.js")
R.c("server/chunks/[root-of-the-server]__0g0zd0c._.js")
R.c("server/chunks/_1ue59d7._.js")
R.c("server/chunks/node_modules_0ub6ovm._.js")
R.c("server/chunks/_next-internal_server_app_api_orders_[id]_approve-binance_route_actions_1g_1awg.js")
R.m(70398)
module.exports=R.m(70398).exports
