// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/account" | "/account/addresses" | "/account/details" | "/account/orders" | "/account/orders/[id]" | "/account/password" | "/admin" | "/admin/banners" | "/admin/categories" | "/admin/coupons" | "/admin/home-manager" | "/admin/menu" | "/admin/orders" | "/admin/orders/[id]" | "/admin/orders/[id]/etiqueta" | "/admin/personalizar" | "/admin/products" | "/admin/reviews" | "/admin/settings" | "/admin/settings/announcement" | "/admin/settings/seo-local" | "/admin/settings/users" | "/admin/stats" | "/buscar" | "/cart" | "/cart/unsubscribe/confirm" | "/categoria/[slug]" | "/checkout" | "/checkout/success" | "/devoluciones" | "/forgot-password" | "/login" | "/nosotros" | "/ofertas" | "/privacy-policy" | "/product/[slug]" | "/productos" | "/register" | "/registro" | "/reset-password" | "/shipping-policy" | "/terms-of-service" | "/tienda-barquisimeto" | "/wishlist"
type AppRouteHandlerRoutes = "/api/account/confirm-email" | "/api/admin/migrate-slugs" | "/api/admin/product-costs" | "/api/auth/[...nextauth]" | "/api/banners" | "/api/banners/[id]" | "/api/cart" | "/api/cart/items" | "/api/cart/items/[productId]" | "/api/cart/merge" | "/api/cart/recover" | "/api/cart/unsubscribe" | "/api/categories" | "/api/categories/[id]" | "/api/categories/sync" | "/api/checkout/upload-proof" | "/api/config/exchange-rate" | "/api/config/homepage" | "/api/coupons" | "/api/coupons/[id]" | "/api/coupons/validate" | "/api/cron/abandoned-cart" | "/api/cron/purge-product-views" | "/api/cron/update-bcv-rate" | "/api/events/top-viewed" | "/api/events/view" | "/api/merchant-feed" | "/api/orders" | "/api/orders/[id]" | "/api/orders/[id]/approve-binance" | "/api/orders/[id]/resend-confirmation" | "/api/orders/[id]/status" | "/api/orders/bulk-status-update" | "/api/orders/export.csv" | "/api/orders/new-count" | "/api/products/[id]/reviews" | "/api/promotions" | "/api/promotions/[id]" | "/api/reviews" | "/api/reviews/[id]" | "/api/reviews/auto-approve" | "/api/reviews/upload-photo" | "/api/settings" | "/api/upload" | "/api/upload-video" | "/api/upload-video/status"
type PageRoutes = never
type LayoutRoutes = "/" | "/account" | "/admin" | "/login"
type RedirectRoutes = "/about" | "/envios" | "/favicon.ico" | "/privacidad" | "/quienes-somos" | "/terminos"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/account": {}
  "/account/addresses": {}
  "/account/details": {}
  "/account/orders": {}
  "/account/orders/[id]": { "id": string; }
  "/account/password": {}
  "/admin": {}
  "/admin/banners": {}
  "/admin/categories": {}
  "/admin/coupons": {}
  "/admin/home-manager": {}
  "/admin/menu": {}
  "/admin/orders": {}
  "/admin/orders/[id]": { "id": string; }
  "/admin/orders/[id]/etiqueta": { "id": string; }
  "/admin/personalizar": {}
  "/admin/products": {}
  "/admin/reviews": {}
  "/admin/settings": {}
  "/admin/settings/announcement": {}
  "/admin/settings/seo-local": {}
  "/admin/settings/users": {}
  "/admin/stats": {}
  "/api/account/confirm-email": {}
  "/api/admin/migrate-slugs": {}
  "/api/admin/product-costs": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/banners": {}
  "/api/banners/[id]": { "id": string; }
  "/api/cart": {}
  "/api/cart/items": {}
  "/api/cart/items/[productId]": { "productId": string; }
  "/api/cart/merge": {}
  "/api/cart/recover": {}
  "/api/cart/unsubscribe": {}
  "/api/categories": {}
  "/api/categories/[id]": { "id": string; }
  "/api/categories/sync": {}
  "/api/checkout/upload-proof": {}
  "/api/config/exchange-rate": {}
  "/api/config/homepage": {}
  "/api/coupons": {}
  "/api/coupons/[id]": { "id": string; }
  "/api/coupons/validate": {}
  "/api/cron/abandoned-cart": {}
  "/api/cron/purge-product-views": {}
  "/api/cron/update-bcv-rate": {}
  "/api/events/top-viewed": {}
  "/api/events/view": {}
  "/api/merchant-feed": {}
  "/api/orders": {}
  "/api/orders/[id]": { "id": string; }
  "/api/orders/[id]/approve-binance": { "id": string; }
  "/api/orders/[id]/resend-confirmation": { "id": string; }
  "/api/orders/[id]/status": { "id": string; }
  "/api/orders/bulk-status-update": {}
  "/api/orders/export.csv": {}
  "/api/orders/new-count": {}
  "/api/products/[id]/reviews": { "id": string; }
  "/api/promotions": {}
  "/api/promotions/[id]": { "id": string; }
  "/api/reviews": {}
  "/api/reviews/[id]": { "id": string; }
  "/api/reviews/auto-approve": {}
  "/api/reviews/upload-photo": {}
  "/api/settings": {}
  "/api/upload": {}
  "/api/upload-video": {}
  "/api/upload-video/status": {}
  "/buscar": {}
  "/cart": {}
  "/cart/unsubscribe/confirm": {}
  "/categoria/[slug]": { "slug": string; }
  "/checkout": {}
  "/checkout/success": {}
  "/devoluciones": {}
  "/envios": {}
  "/favicon.ico": {}
  "/forgot-password": {}
  "/login": {}
  "/nosotros": {}
  "/ofertas": {}
  "/privacidad": {}
  "/privacy-policy": {}
  "/product/[slug]": { "slug": string; }
  "/productos": {}
  "/quienes-somos": {}
  "/register": {}
  "/registro": {}
  "/reset-password": {}
  "/shipping-policy": {}
  "/terminos": {}
  "/terms-of-service": {}
  "/tienda-barquisimeto": {}
  "/wishlist": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/account": never
  "/admin": never
  "/login": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
