// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/account/addresses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/addresses">> = Specific
  const handler = {} as typeof import("../../app/account/addresses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/account/details/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/details">> = Specific
  const handler = {} as typeof import("../../app/account/details/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/account/orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/orders/[id]">> = Specific
  const handler = {} as typeof import("../../app/account/orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/account/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/orders">> = Specific
  const handler = {} as typeof import("../../app/account/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account">> = Specific
  const handler = {} as typeof import("../../app/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/account/password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/password">> = Specific
  const handler = {} as typeof import("../../app/account/password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/banners/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/banners">> = Specific
  const handler = {} as typeof import("../../app/admin/banners/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/categories">> = Specific
  const handler = {} as typeof import("../../app/admin/categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/coupons/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/coupons">> = Specific
  const handler = {} as typeof import("../../app/admin/coupons/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/home-manager/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/home-manager">> = Specific
  const handler = {} as typeof import("../../app/admin/home-manager/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/menu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/menu">> = Specific
  const handler = {} as typeof import("../../app/admin/menu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/orders/[id]/etiqueta/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/orders/[id]/etiqueta">> = Specific
  const handler = {} as typeof import("../../app/admin/orders/[id]/etiqueta/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/orders/[id]">> = Specific
  const handler = {} as typeof import("../../app/admin/orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/orders">> = Specific
  const handler = {} as typeof import("../../app/admin/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/personalizar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/personalizar">> = Specific
  const handler = {} as typeof import("../../app/admin/personalizar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/products">> = Specific
  const handler = {} as typeof import("../../app/admin/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reviews">> = Specific
  const handler = {} as typeof import("../../app/admin/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/settings/announcement/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings/announcement">> = Specific
  const handler = {} as typeof import("../../app/admin/settings/announcement/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/settings/seo-local/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings/seo-local">> = Specific
  const handler = {} as typeof import("../../app/admin/settings/seo-local/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/settings/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings/users">> = Specific
  const handler = {} as typeof import("../../app/admin/settings/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/stats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/stats">> = Specific
  const handler = {} as typeof import("../../app/admin/stats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/buscar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/buscar">> = Specific
  const handler = {} as typeof import("../../app/buscar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cart">> = Specific
  const handler = {} as typeof import("../../app/cart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cart/unsubscribe/confirm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cart/unsubscribe/confirm">> = Specific
  const handler = {} as typeof import("../../app/cart/unsubscribe/confirm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/categoria/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/categoria/[slug]">> = Specific
  const handler = {} as typeof import("../../app/categoria/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout">> = Specific
  const handler = {} as typeof import("../../app/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/checkout/success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout/success">> = Specific
  const handler = {} as typeof import("../../app/checkout/success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/devoluciones/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/devoluciones">> = Specific
  const handler = {} as typeof import("../../app/devoluciones/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../app/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/nosotros/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nosotros">> = Specific
  const handler = {} as typeof import("../../app/nosotros/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ofertas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ofertas">> = Specific
  const handler = {} as typeof import("../../app/ofertas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/privacy-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy-policy">> = Specific
  const handler = {} as typeof import("../../app/privacy-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/product/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/product/[slug]">> = Specific
  const handler = {} as typeof import("../../app/product/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/productos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/productos">> = Specific
  const handler = {} as typeof import("../../app/productos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/registro/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/registro">> = Specific
  const handler = {} as typeof import("../../app/registro/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/shipping-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shipping-policy">> = Specific
  const handler = {} as typeof import("../../app/shipping-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/terms-of-service/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms-of-service">> = Specific
  const handler = {} as typeof import("../../app/terms-of-service/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/tienda-barquisimeto/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tienda-barquisimeto">> = Specific
  const handler = {} as typeof import("../../app/tienda-barquisimeto/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/wishlist/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wishlist">> = Specific
  const handler = {} as typeof import("../../app/wishlist/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/account/confirm-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/confirm-email">> = Specific
  const handler = {} as typeof import("../../app/api/account/confirm-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/migrate-slugs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/migrate-slugs">> = Specific
  const handler = {} as typeof import("../../app/api/admin/migrate-slugs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/product-costs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/product-costs">> = Specific
  const handler = {} as typeof import("../../app/api/admin/product-costs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/banners/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/banners/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/banners/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/banners/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/banners">> = Specific
  const handler = {} as typeof import("../../app/api/banners/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cart/items/[productId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cart/items/[productId]">> = Specific
  const handler = {} as typeof import("../../app/api/cart/items/[productId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cart/items/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cart/items">> = Specific
  const handler = {} as typeof import("../../app/api/cart/items/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cart/merge/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cart/merge">> = Specific
  const handler = {} as typeof import("../../app/api/cart/merge/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cart/recover/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cart/recover">> = Specific
  const handler = {} as typeof import("../../app/api/cart/recover/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cart/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cart">> = Specific
  const handler = {} as typeof import("../../app/api/cart/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cart/unsubscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cart/unsubscribe">> = Specific
  const handler = {} as typeof import("../../app/api/cart/unsubscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/categories/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/categories/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/categories/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/categories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/categories">> = Specific
  const handler = {} as typeof import("../../app/api/categories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/categories/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/categories/sync">> = Specific
  const handler = {} as typeof import("../../app/api/categories/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/checkout/upload-proof/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/checkout/upload-proof">> = Specific
  const handler = {} as typeof import("../../app/api/checkout/upload-proof/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/config/exchange-rate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/config/exchange-rate">> = Specific
  const handler = {} as typeof import("../../app/api/config/exchange-rate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/config/homepage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/config/homepage">> = Specific
  const handler = {} as typeof import("../../app/api/config/homepage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/coupons/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/coupons/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/coupons/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/coupons/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/coupons">> = Specific
  const handler = {} as typeof import("../../app/api/coupons/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/coupons/validate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/coupons/validate">> = Specific
  const handler = {} as typeof import("../../app/api/coupons/validate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cron/abandoned-cart/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/abandoned-cart">> = Specific
  const handler = {} as typeof import("../../app/api/cron/abandoned-cart/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cron/purge-product-views/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/purge-product-views">> = Specific
  const handler = {} as typeof import("../../app/api/cron/purge-product-views/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cron/update-bcv-rate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/update-bcv-rate">> = Specific
  const handler = {} as typeof import("../../app/api/cron/update-bcv-rate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/events/top-viewed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/top-viewed">> = Specific
  const handler = {} as typeof import("../../app/api/events/top-viewed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/events/view/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/view">> = Specific
  const handler = {} as typeof import("../../app/api/events/view/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/merchant-feed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/merchant-feed">> = Specific
  const handler = {} as typeof import("../../app/api/merchant-feed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/[id]/approve-binance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]/approve-binance">> = Specific
  const handler = {} as typeof import("../../app/api/orders/[id]/approve-binance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/[id]/resend-confirmation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]/resend-confirmation">> = Specific
  const handler = {} as typeof import("../../app/api/orders/[id]/resend-confirmation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/orders/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]/status">> = Specific
  const handler = {} as typeof import("../../app/api/orders/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/bulk-status-update/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/bulk-status-update">> = Specific
  const handler = {} as typeof import("../../app/api/orders/bulk-status-update/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/export.csv/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/export.csv">> = Specific
  const handler = {} as typeof import("../../app/api/orders/export.csv/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/new-count/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/new-count">> = Specific
  const handler = {} as typeof import("../../app/api/orders/new-count/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders">> = Specific
  const handler = {} as typeof import("../../app/api/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/products/[id]/reviews/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/[id]/reviews">> = Specific
  const handler = {} as typeof import("../../app/api/products/[id]/reviews/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/promotions/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/promotions/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/promotions/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/promotions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/promotions">> = Specific
  const handler = {} as typeof import("../../app/api/promotions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reviews/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reviews/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/reviews/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reviews/auto-approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reviews/auto-approve">> = Specific
  const handler = {} as typeof import("../../app/api/reviews/auto-approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reviews/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reviews">> = Specific
  const handler = {} as typeof import("../../app/api/reviews/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reviews/upload-photo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reviews/upload-photo">> = Specific
  const handler = {} as typeof import("../../app/api/reviews/upload-photo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings">> = Specific
  const handler = {} as typeof import("../../app/api/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/upload-video/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload-video">> = Specific
  const handler = {} as typeof import("../../app/api/upload-video/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/upload-video/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload-video/status">> = Specific
  const handler = {} as typeof import("../../app/api/upload-video/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload">> = Specific
  const handler = {} as typeof import("../../app/api/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/account/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/account">> = Specific
  const handler = {} as typeof import("../../app/account/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
