var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/events/view/route.js")
R.c("server/chunks/[root-of-the-server]__0wh8ax9._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/_1n7i2mp._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_1-pw2v2.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/[root-of-the-server]__0g0zd0c._.js")
R.c("server/chunks/_next-internal_server_app_api_events_view_route_actions_0qx9gvd.js")
R.m(262614)
module.exports=R.m(262614).exports
