var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/promotions/route.js")
R.c("server/chunks/[root-of-the-server]__1ex7k27._.js")
R.c("server/chunks/_1n7i2mp._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_1-pw2v2.js")
R.c("server/chunks/node_modules_next_1ir7qn-._.js")
R.c("server/chunks/_0o550kv._.js")
R.c("server/chunks/[root-of-the-server]__0g0zd0c._.js")
R.c("server/chunks/_next-internal_server_app_api_promotions_route_actions_11hhvxi.js")
R.m(615926)
module.exports=R.m(615926).exports
