var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/product-costs/route.js")
R.c("server/chunks/[root-of-the-server]__1-f5kqx._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/_1n7i2mp._.js")
R.c("server/chunks/[root-of-the-server]__0g0zd0c._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/_0o550kv._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_product-costs_route_actions_04czean.js")
R.m(17056)
module.exports=R.m(17056).exports
