var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/checkout/upload-proof/route.js")
R.c("server/chunks/[root-of-the-server]__0hq3lfx._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/_1n7i2mp._.js")
R.c("server/chunks/_0o550kv._.js")
R.c("server/chunks/[root-of-the-server]__0g0zd0c._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/_next-internal_server_app_api_checkout_upload-proof_route_actions_1n_liny.js")
R.m(133971)
module.exports=R.m(133971).exports
