var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/orders/bulk-status-update/route.js")
R.c("server/chunks/lib_1w5bl52._.js")
R.c("server/chunks/[root-of-the-server]__1s1xuua._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/_1n7i2mp._.js")
R.c("server/chunks/_0piksd_._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_1-pw2v2.js")
R.c("server/chunks/_0o550kv._.js")
R.c("server/chunks/[root-of-the-server]__0g0zd0c._.js")
R.c("server/chunks/node_modules_0ub6ovm._.js")
R.c("server/chunks/_next-internal_server_app_api_orders_bulk-status-update_route_actions_1vt30b-.js")
R.m(670277)
module.exports=R.m(670277).exports
