var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/orders/route.js")
R.c("server/chunks/lib_1w5bl52._.js")
R.c("server/chunks/_0rwoq_j._.js")
R.c("server/chunks/_1n7i2mp._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/[root-of-the-server]__1kd_gdi._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_1-pw2v2.js")
R.c("server/chunks/_0o550kv._.js")
R.c("server/chunks/[root-of-the-server]__0g0zd0c._.js")
R.c("server/chunks/node_modules_0ub6ovm._.js")
R.c("server/chunks/_1ue59d7._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/_next-internal_server_app_api_orders_route_actions_18oip2y.js")
R.m(981585)
module.exports=R.m(981585).exports
