var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/merchant-feed/route.js")
R.c("server/chunks/[root-of-the-server]__1r6muyw._.js")
R.c("server/chunks/_1n7i2mp._.js")
R.c("server/chunks/_1tdd4gn._.js")
R.c("server/chunks/[root-of-the-server]__0g0zd0c._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_1-pw2v2.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/_next-internal_server_app_api_merchant-feed_route_actions_0gs52jn.js")
R.m(530761)
module.exports=R.m(530761).exports
