var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/events/top-viewed/route.js")
R.c("server/chunks/[root-of-the-server]__16kqbpq._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/_1n7i2mp._.js")
R.c("server/chunks/[root-of-the-server]__0g0zd0c._.js")
R.c("server/chunks/_0o550kv._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/_next-internal_server_app_api_events_top-viewed_route_actions_14ukob6.js")
R.m(637693)
module.exports=R.m(637693).exports
